development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: covidchat_development

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV['REDISCLOUD_URL'] || ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: covidchat_production
